apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  console:
    expose: true
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
    verifyHost: false
    expose: true
  - name: mqtt
    protocols: mqtt
    port: 8883
    sslEnabled: true
    verifyHost: false
    expose: true
